### ISSUE TITLE
move to events

### ISSUE THREAD

**Issue by sreehari2003** [foss-labs/fossfolio#147]
https://github.com/DarkPhoenix2704/fossfolio/blob/9c2cc31bea4a0611e42c5fb594edb9da52f0d8da/apps/api/src/events/events.service.ts#L82

**Comment by DarkPhoenix2704** [comment]
![logo](https://github.com/DarkPhoenix2704/fossfolio/assets/64391274/5a5b7805-d792-4cb7-8738-b561ca4ea6f8)

**Comment by DarkPhoenix2704** [comment]
@DarkPhoenix2704
